// Dummy data for team members
export const teamMembers = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    role: "Admin",
    status: "active",
    lastActive: "Just now",
    avatar: "JD",
    articles: 24,
    joined: "Jan 15, 2023",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    email: "sarah.j@example.com",
    role: "Editor",
    status: "active",
    lastActive: "2 hours ago",
    avatar: "SJ",
    articles: 18,
    joined: "Feb 3, 2023",
  },
  {
    id: 3,
    name: "Michael Chen",
    email: "michael.c@example.com",
    role: "Writer",
    status: "active",
    lastActive: "1 day ago",
    avatar: "MC",
    articles: 12,
    joined: "Mar 20, 2023",
  },
  {
    id: 4,
    name: "Emily Wilson",
    email: "emily.w@example.com",
    role: "Writer",
    status: "inactive",
    lastActive: "5 days ago",
    avatar: "EW",
    articles: 7,
    joined: "Apr 12, 2023",
  },
  {
    id: 5,
    name: "David Rodriguez",
    email: "david.r@example.com",
    role: "SEO Specialist",
    status: "pending",
    lastActive: "Never",
    avatar: "DR",
    articles: 0,
    joined: "May 5, 2023",
  },
];

// Dummy data for team activity
export const teamActivity = [
  {
    id: 1,
    user: "John Doe",
    action: "published an article",
    target: "7 Leading AI SEO Tools in 2024",
    time: "10 minutes ago",
    avatar: "JD",
  },
  {
    id: 2,
    user: "Sarah Johnson",
    action: "edited an article",
    target: "Backlinks 101: What are backlinks",
    time: "2 hours ago",
    avatar: "SJ",
  },
  {
    id: 3,
    user: "Michael Chen",
    action: "added keywords",
    target: "15 new keywords to research list",
    time: "Yesterday at 4:30 PM",
    avatar: "MC",
  },
  {
    id: 4,
    user: "John Doe",
    action: "invited a team member",
    target: "David Rodriguez",
    time: "2 days ago",
    avatar: "JD",
  },
  {
    id: 5,
    user: "Sarah Johnson",
    action: "updated team settings",
    target: "Changed notification preferences",
    time: "3 days ago",
    avatar: "SJ",
  },
];
