export const articles = [
  {
    id: 1,
    title: "How to Improve Your Skills in League of Legends",
    keyword: "league of legends [2240000]",
    words: 4575,
    createdOn: "20 hours ago",
  },
  {
    id: 2,
    title: "How to Master Last Hitting in League of Legends",
    keyword: "league of legends [2240000]",
    words: 3480,
    createdOn: "21 hours ago",
  },
  {
    id: 3,
    title: "7 Tips for Better Teamplay in League of Legends",
    keyword: "league of legends [2240000]",
    words: 2676,
    createdOn: "4 days ago",
  },
  {
    id: 4,
    title: "Top Virtual Executive Assistant Services (2024)",
    keyword: "virtual executive assistant [2300]",
    words: 2408,
    createdOn: "1 Oct, 24",
  },
  {
    id: 5,
    title: "Unlimited Graphics Design Solutions",
    keyword: "unlimited graphic design services [930]",
    words: 1733,
    createdOn: "--",
  },
  {
    id: 6,
    title: "Top Amazon Payment Methods for Quick Access to Funds",
    keyword: "amazon payment methods [3600]",
    words: 2627,
    createdOn: "--",
  },
  {
    id: 7,
    title:
      "Backlinks 101: What are backlinks and why they're important [Free template]",
    keyword: "backlinks [8900]",
    words: 2261,
    createdOn: "--",
  },
  {
    id: 8,
    title: "7 Leading AI SEO Tools in 2024 (Ranked & Compared)",
    keyword: "ai seo software [880]",
    words: 1543,
    createdOn: "--",
  },
  {
    id: 9,
    title: "Unlimited Graphic Design Services You Can Rely On",
    keyword: "unlimited graphic design services [930]",
    words: 1974,
    createdOn: "--",
  },
];

export const requestedFeatures = [
  {
    id: 1,
    title: "AI-powered content optimization",
    description:
      "Add AI tools to automatically optimize content for SEO and readability.",
    votes: 142,
    status: "planned",
    date: "2 weeks ago",
  },
  {
    id: 2,
    title: "Bulk article editor",
    description: "Allow editing multiple articles at once to save time.",
    votes: 98,
    status: "in-progress",
    date: "1 month ago",
  },
  {
    id: 3,
    title: "Content calendar integration",
    description:
      "Integrate with Google Calendar and other calendar apps for content scheduling.",
    votes: 76,
    status: "planned",
    date: "3 weeks ago",
  },
  {
    id: 4,
    title: "Advanced analytics dashboard",
    description:
      "Provide more detailed analytics on article performance, traffic, and engagement.",
    votes: 65,
    status: "completed",
    date: "2 months ago",
  },
  {
    id: 5,
    title: "Competitor analysis tool",
    description:
      "Add tools to analyze competitor content and identify gaps in your strategy.",
    votes: 54,
    status: "planned",
    date: "1 month ago",
  },
  {
    id: 6,
    title: "Mobile app for content management",
    description: "Create a mobile app to manage content on the go.",
    votes: 47,
    status: "under-review",
    date: "2 weeks ago",
  },
];

export const keywords = [
  {
    id: 1,
    keyword: "league of legends",
    volume: 2300000,
    difficulty: 78,
    cpc: 1.24,
    intent: "informational",
    trend: "stable",
  },
  {
    id: 2,
    keyword: "league of legends guide",
    volume: 74000,
    difficulty: 65,
    cpc: 0.95,
    intent: "informational",
    trend: "increasing",
  },
  {
    id: 3,
    keyword: "league of legends champions",
    volume: 165000,
    difficulty: 72,
    cpc: 1.05,
    intent: "navigational",
    trend: "stable",
  },
  {
    id: 4,
    keyword: "best league of legends champions",
    volume: 33000,
    difficulty: 58,
    cpc: 1.35,
    intent: "commercial",
    trend: "increasing",
  },
  {
    id: 5,
    keyword: "league of legends tier list",
    volume: 110000,
    difficulty: 62,
    cpc: 0.88,
    intent: "informational",
    trend: "increasing",
  },
  {
    id: 6,
    keyword: "virtual assistant services",
    volume: 22000,
    difficulty: 54,
    cpc: 4.75,
    intent: "commercial",
    trend: "increasing",
  },
  {
    id: 7,
    keyword: "graphic design services",
    volume: 40500,
    difficulty: 67,
    cpc: 5.2,
    intent: "transactional",
    trend: "stable",
  },
  {
    id: 8,
    keyword: "backlinks seo",
    volume: 18000,
    difficulty: 59,
    cpc: 3.45,
    intent: "informational",
    trend: "stable",
  },
];
