export const competitors = [
  {
    id: 1,
    name: "gamingguides.com",
    keywords: 1245,
    traffic: 345000,
    domain: 72,
  },
  {
    id: 2,
    name: "leagueoflegendstips.net",
    keywords: 876,
    traffic: 215000,
    domain: 65,
  },
  {
    id: 3,
    name: "esportshub.io",
    keywords: 1532,
    traffic: 420000,
    domain: 78,
  },
];

export const competitorKeywords = [
  {
    id: 1,
    keyword: "league of legends best champions",
    volume: 18000,
    difficulty: 62,
    position: 3,
    competitor: "gamingguides.com",
    gap: true,
  },
  {
    id: 2,
    keyword: "league of legends tier list 2024",
    volume: 22000,
    difficulty: 58,
    position: 1,
    competitor: "leagueoflegendstips.net",
    gap: true,
  },
  {
    id: 3,
    keyword: "how to climb in league of legends",
    volume: 9500,
    difficulty: 45,
    position: 2,
    competitor: "gamingguides.com",
    gap: true,
  },
  {
    id: 4,
    keyword: "league of legends pro builds",
    volume: 14500,
    difficulty: 53,
    position: 4,
    competitor: "esportshub.io",
    gap: false,
  },
  {
    id: 5,
    keyword: "league of legends patch notes",
    volume: 33000,
    difficulty: 67,
    position: 2,
    competitor: "esportshub.io",
    gap: false,
  },
  {
    id: 6,
    keyword: "league of legends beginner guide",
    volume: 8200,
    difficulty: 42,
    position: 5,
    competitor: "leagueoflegendstips.net",
    gap: true,
  },
  {
    id: 7,
    keyword: "best league of legends settings",
    volume: 6700,
    difficulty: 38,
    position: 3,
    competitor: "gamingguides.com",
    gap: true,
  },
];
